// AUTO-GENERATED by scripts/build-data.mjs from the real Alpine parquet data
// (Darpenss/P1 outputs + source-data). Do not edit by hand — re-run the script.
// Source: alpine-manufacturing-gmbh · forecast cutoff 2026-04-01, horizon 2026-05-01

export interface Product {
  product_id: string;
  name: string;
  business_unit: string;
  category: string;
  abc_class: string;
  margin_pct: number | null;
}
export interface SalesOrg {
  sales_org_id: string;
  name: string;
  region_group: string;
  country: string;
}

export const FORECAST_CUTOFF = "2026-04-01";
export const FORECAST_MONTH = "2026-05-01";

export const PRODUCTS: Product[] = [
  {
    "product_id": "CP-0271",
    "name": "Premium Drills Mark II 1",
    "business_unit": "Consumer Products",
    "category": "Power Tools",
    "abc_class": "C",
    "margin_pct": 27
  },
  {
    "product_id": "PC-0079",
    "name": "Schnorr S-08 Spring Washer II",
    "business_unit": "Precision Components",
    "category": "Fasteners & Connectors",
    "abc_class": "C",
    "margin_pct": 17
  },
  {
    "product_id": "PC-0100",
    "name": "Heico-Lock M10 Wedge Washer VI",
    "business_unit": "Precision Components",
    "category": "Fasteners & Connectors",
    "abc_class": "A",
    "margin_pct": 31
  },
  {
    "product_id": "PC-0092",
    "name": "Würth M16 Flange Nut V",
    "business_unit": "Precision Components",
    "category": "Fasteners & Connectors",
    "abc_class": "B",
    "margin_pct": 29
  },
  {
    "product_id": "PC-0061",
    "name": "Elite Bolts Line 10",
    "business_unit": "Precision Components",
    "category": "Fasteners & Connectors",
    "abc_class": "C",
    "margin_pct": 31
  },
  {
    "product_id": "PC-0102",
    "name": "Precision Cable XL 5",
    "business_unit": "Precision Components",
    "category": "Fasteners & Connectors",
    "abc_class": "B",
    "margin_pct": 32
  },
  {
    "product_id": "CP-0369",
    "name": "Flex Screwdrivers HD 13",
    "business_unit": "Consumer Products",
    "category": "Hand Tools",
    "abc_class": "B",
    "margin_pct": 25
  }
];
export const SALES_ORGS: SalesOrg[] = [
  {
    "sales_org_id": "SO01",
    "name": "Germany Central",
    "region_group": "DACH",
    "country": "DE"
  },
  {
    "sales_org_id": "SO02",
    "name": "Germany North",
    "region_group": "DACH",
    "country": "DE"
  },
  {
    "sales_org_id": "SO03",
    "name": "Germany South",
    "region_group": "DACH",
    "country": "DE"
  },
  {
    "sales_org_id": "SO04",
    "name": "Austria",
    "region_group": "DACH",
    "country": "AT"
  },
  {
    "sales_org_id": "SO05",
    "name": "Switzerland",
    "region_group": "DACH",
    "country": "CH"
  },
  {
    "sales_org_id": "SO06",
    "name": "Netherlands",
    "region_group": "BeNeLux",
    "country": "NL"
  },
  {
    "sales_org_id": "SO07",
    "name": "Belgium",
    "region_group": "BeNeLux",
    "country": "BE"
  },
  {
    "sales_org_id": "SO08",
    "name": "France",
    "region_group": "Western EU",
    "country": "FR"
  },
  {
    "sales_org_id": "SO09",
    "name": "Italy",
    "region_group": "Southern EU",
    "country": "IT"
  },
  {
    "sales_org_id": "SO10",
    "name": "Spain",
    "region_group": "Southern EU",
    "country": "ES"
  },
  {
    "sales_org_id": "SO11",
    "name": "Sweden",
    "region_group": "Nordics",
    "country": "SE"
  },
  {
    "sales_org_id": "SO12",
    "name": "Denmark",
    "region_group": "Nordics",
    "country": "DK"
  },
  {
    "sales_org_id": "SO13",
    "name": "Norway",
    "region_group": "Nordics",
    "country": "NO"
  },
  {
    "sales_org_id": "SO14",
    "name": "Poland",
    "region_group": "Eastern EU",
    "country": "PL"
  },
  {
    "sales_org_id": "SO15",
    "name": "Czech Republic",
    "region_group": "Eastern EU",
    "country": "CZ"
  },
  {
    "sales_org_id": "SO16",
    "name": "UK",
    "region_group": "UK",
    "country": "GB"
  },
  {
    "sales_org_id": "SO17",
    "name": "Portugal",
    "region_group": "Southern EU",
    "country": "PT"
  },
  {
    "sales_org_id": "SO18",
    "name": "Finland",
    "region_group": "Nordics",
    "country": "FI"
  }
];

// machine[product_id][sales_org_id] = real statistical forecast (units, H+1)
export const MACHINE_FORECAST: Record<string, Record<string, number>> = {
  "CP-0271": {
    "SO02": 574,
    "SO04": 304,
    "SO08": 379,
    "SO10": 200,
    "SO11": 197,
    "SO13": 113,
    "SO15": 103,
    "SO17": 106
  },
  "PC-0079": {
    "SO01": 1453380,
    "SO03": 1072338
  },
  "PC-0100": {
    "SO02": 347657,
    "SO04": 213797,
    "SO05": 170197,
    "SO08": 281661,
    "SO10": 155596,
    "SO11": 142735,
    "SO13": 66528,
    "SO14": 147863,
    "SO15": 69649,
    "SO16": 189562,
    "SO17": 58828,
    "SO18": 75521
  },
  "PC-0092": {
    "SO03": 569690,
    "SO04": 323262,
    "SO08": 379081,
    "SO09": 299912
  },
  "PC-0061": {
    "SO01": 328246,
    "SO02": 207149,
    "SO04": 143805,
    "SO05": 104892,
    "SO07": 66940,
    "SO09": 136368,
    "SO10": 106408,
    "SO11": 98244,
    "SO12": 73157,
    "SO13": 56379,
    "SO14": 90936,
    "SO15": 52512,
    "SO18": 54938
  },
  "PC-0102": {
    "SO02": 228456,
    "SO03": 238377,
    "SO06": 110156,
    "SO07": 59178,
    "SO08": 176262,
    "SO10": 75498,
    "SO11": 83772,
    "SO13": 37872,
    "SO18": 42706
  },
  "CP-0369": {
    "SO02": 238837,
    "SO05": 117678,
    "SO08": 208699,
    "SO11": 90937,
    "SO13": 43292,
    "SO14": 85288,
    "SO17": 53729,
    "SO18": 55055
  }
};
