// AUTO-GENERATED by scripts/build-data.mjs from the real Alpine parquet data
// (Darpenss/P1 outputs + source-data). Do not edit by hand — re-run the script.
// Source: alpine-manufacturing-gmbh · forecast cutoff 2026-04-01, horizon 2026-05-01

export interface ReplayCycle {
  cutoff_date: string;
  mae_machine: number;
  mae_planner: number;
  mae_compass: number;
  wape_machine: number;
  wape_planner: number;
  pct_helped: number;
}

export const HEADLINE = {
  "method": "H+1 full-month comparison; actuals aggregated across channels",
  "cutoffs": 23,
  "total_rows": 68126,
  "exact_override_share": 0.9982385579661216,
  "meaningful_override_threshold": 0.05,
  "meaningful_override_share": 0.7566421043360831,
  "median_abs_meaningful_override_pct": 0.13859556494192188,
  "downward_share_meaningful": 0.44980309232351057,
  "pct_helped_all": 0.6136717259196195,
  "pct_helped_meaningful": 0.6432770093312898,
  "mae_machine": 2013.3191072424625,
  "mae_planner": 1574.0618647799665,
  "wape_machine": 0.19171073153030882,
  "wape_planner": 0.14988411448806072
} as const;

export const REPLAY: ReplayCycle[] = [
  {
    "cutoff_date": "2024-05-01",
    "mae_machine": 1721,
    "mae_planner": 1372,
    "wape_machine": 0.1784,
    "wape_planner": 0.1422,
    "pct_helped": 0.554,
    "mae_compass": 1372
  },
  {
    "cutoff_date": "2024-06-01",
    "mae_machine": 1841,
    "mae_planner": 1944,
    "wape_machine": 0.1618,
    "wape_planner": 0.171,
    "pct_helped": 0.5773,
    "mae_compass": 1813
  },
  {
    "cutoff_date": "2024-07-01",
    "mae_machine": 1899,
    "mae_planner": 1667,
    "wape_machine": 0.2102,
    "wape_planner": 0.1845,
    "pct_helped": 0.5763,
    "mae_compass": 1667
  },
  {
    "cutoff_date": "2024-08-01",
    "mae_machine": 2674,
    "mae_planner": 1635,
    "wape_machine": 0.2176,
    "wape_planner": 0.1331,
    "pct_helped": 0.8528,
    "mae_compass": 1635
  },
  {
    "cutoff_date": "2024-09-01",
    "mae_machine": 1572,
    "mae_planner": 1355,
    "wape_machine": 0.1598,
    "wape_planner": 0.1377,
    "pct_helped": 0.5415,
    "mae_compass": 1355
  },
  {
    "cutoff_date": "2024-10-01",
    "mae_machine": 1583,
    "mae_planner": 1353,
    "wape_machine": 0.1592,
    "wape_planner": 0.1361,
    "pct_helped": 0.503,
    "mae_compass": 1353
  },
  {
    "cutoff_date": "2024-11-01",
    "mae_machine": 1861,
    "mae_planner": 1868,
    "wape_machine": 0.1639,
    "wape_planner": 0.1646,
    "pct_helped": 0.5594,
    "mae_compass": 1833
  },
  {
    "cutoff_date": "2024-12-01",
    "mae_machine": 1533,
    "mae_planner": 1331,
    "wape_machine": 0.1584,
    "wape_planner": 0.1375,
    "pct_helped": 0.553,
    "mae_compass": 1331
  },
  {
    "cutoff_date": "2025-01-01",
    "mae_machine": 1582,
    "mae_planner": 1384,
    "wape_machine": 0.1608,
    "wape_planner": 0.1407,
    "pct_helped": 0.5324,
    "mae_compass": 1384
  },
  {
    "cutoff_date": "2025-02-01",
    "mae_machine": 3167,
    "mae_planner": 1731,
    "wape_machine": 0.2461,
    "wape_planner": 0.1345,
    "pct_helped": 0.9227,
    "mae_compass": 1731
  },
  {
    "cutoff_date": "2025-03-01",
    "mae_machine": 1416,
    "mae_planner": 1455,
    "wape_machine": 0.1376,
    "wape_planner": 0.1414,
    "pct_helped": 0.4743,
    "mae_compass": 1395
  },
  {
    "cutoff_date": "2025-04-01",
    "mae_machine": 1606,
    "mae_planner": 1327,
    "wape_machine": 0.1624,
    "wape_planner": 0.1343,
    "pct_helped": 0.5304,
    "mae_compass": 1327
  },
  {
    "cutoff_date": "2025-05-01",
    "mae_machine": 2946,
    "mae_planner": 1601,
    "wape_machine": 0.2341,
    "wape_planner": 0.1272,
    "pct_helped": 0.8673,
    "mae_compass": 1601
  },
  {
    "cutoff_date": "2025-06-01",
    "mae_machine": 1873,
    "mae_planner": 1494,
    "wape_machine": 0.1994,
    "wape_planner": 0.159,
    "pct_helped": 0.5564,
    "mae_compass": 1494
  },
  {
    "cutoff_date": "2025-07-01",
    "mae_machine": 1797,
    "mae_planner": 1528,
    "wape_machine": 0.1935,
    "wape_planner": 0.1646,
    "pct_helped": 0.5672,
    "mae_compass": 1528
  },
  {
    "cutoff_date": "2025-08-01",
    "mae_machine": 2905,
    "mae_planner": 1633,
    "wape_machine": 0.2313,
    "wape_planner": 0.13,
    "pct_helped": 0.8569,
    "mae_compass": 1633
  },
  {
    "cutoff_date": "2025-09-01",
    "mae_machine": 1490,
    "mae_planner": 1357,
    "wape_machine": 0.1489,
    "wape_planner": 0.1357,
    "pct_helped": 0.5233,
    "mae_compass": 1357
  },
  {
    "cutoff_date": "2025-10-01",
    "mae_machine": 1452,
    "mae_planner": 1460,
    "wape_machine": 0.1417,
    "wape_planner": 0.1424,
    "pct_helped": 0.4916,
    "mae_compass": 1431
  },
  {
    "cutoff_date": "2025-11-01",
    "mae_machine": 2166,
    "mae_planner": 1689,
    "wape_machine": 0.1851,
    "wape_planner": 0.1443,
    "pct_helped": 0.6074,
    "mae_compass": 1689
  },
  {
    "cutoff_date": "2025-12-01",
    "mae_machine": 1679,
    "mae_planner": 1316,
    "wape_machine": 0.176,
    "wape_planner": 0.1379,
    "pct_helped": 0.5722,
    "mae_compass": 1316
  },
  {
    "cutoff_date": "2026-01-01",
    "mae_machine": 1538,
    "mae_planner": 1378,
    "wape_machine": 0.1576,
    "wape_planner": 0.1412,
    "pct_helped": 0.527,
    "mae_compass": 1378
  },
  {
    "cutoff_date": "2026-02-01",
    "mae_machine": 2966,
    "mae_planner": 1783,
    "wape_machine": 0.2328,
    "wape_planner": 0.1399,
    "pct_helped": 0.7779,
    "mae_compass": 1783
  },
  {
    "cutoff_date": "2026-03-01",
    "mae_machine": 3041,
    "mae_planner": 2544,
    "wape_machine": 0.3952,
    "wape_planner": 0.3306,
    "pct_helped": 0.5901,
    "mae_compass": 2544
  }
];
